# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: 'latest-$(BuildID)'

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    filePath: '.\Tools\AzurePreBuild.ps1'
  env: 
    RSL_VERSION: 'latest-$(BuildID)'

- task: VSBuild@1
  inputs:
    solution: '.\RSL.sln'
    vsVersion: '16.0'
    platform: 'x86'
    configuration: 'Appveyor'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

- task: PowerShell@2
  inputs:
    filePath: '.\Tools\AzurePostBuild.ps1'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\Red Faction Guerrilla Re-Mars-tered'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(BuildID).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(BuildID).zip'
    artifact: 'latest-$(BuildID)'