return {
    ["None"] = 4294967295,
    ["Ammo"] = 0,
    ["Clip"] = 1,
    ["Accessory"] = 2,
    ["Scope"] = 3,
    ["Silencer"] = 4,
    ["CodeDesignated"] = 5,
    ["HeadProp"] = 6,
    ["Grenade1"] = 7,
    ["Grenade2"] = 8,
    ["Grenade3"] = 9,
    ["AccessoryMisc"] = 10,
    ["SatchelCharge"] = 11,
    ["EyeWear"] = 12,
    ["Torso"] = 13,
    ["EarRing1"] = 14,
    ["EarRing2"] = 15,
    ["Waist"] = 16,
    ["Jetpack"] = 17,
    ["MpFlag"] = 18,
    ["Back"] = 19,
    ["NumPropTypes"] = 20,
}