#pragma once
#include "RFGR_Types_Vfx_Template.h"

enum event_type
{
    EVENT_UNDEFINED = 0xFFFFFFFF,
    EVENT_BUILDING_DAMAGED = 0x0,
    EVENT_BUILDING_DAMAGED_BY_EXPLOSION = 0x1,
    EVENT_BUILDING_DESTROYED = 0x2,
    EVENT_SALVAGE_CREATED = 0x3,
    EVENT_WEAPON_ACQUIRED = 0x4,
    EVENT_AMMO_ACQUIRED = 0x5,
    EVENT_ITEM_ACQUIRED = 0x6,
    EVENT_RAID_COMPLETE = 0x7,
    EVENT_ACTIVITY_STATE_CHANGE = 0x8,
    EVENT_RAID_STATE_CHANGE = 0x9,
    EVENT_HOUSE_ARREST_STATUS = 0xA,
    EVENT_TURRET_DESTROYED = 0xB,
    EVENT_VEHICLE_DESTROYED = 0xC,
    EVENT_HUMAN_DEAD = 0xD,
    EVENT_DIALOGUE_FINISHED = 0xE,
    EVENT_EDF_CONTROL_LOWERED = 0xF,
    EVENT_CIVILIAN_MORALE_LOWERED = 0x10,
    EVENT_CIVILIAN_MORALE_RAISED = 0x11,
    EVENT_PLAYER_ENTER_TRIGGER_REGION = 0x12,
    EVENT_PLAYER_EXIT_TRIGGER_REGION = 0x13,
    EVENT_OBJECT_ENTER_TRIGGER_REGION = 0x14,
    EVENT_OBJECT_EXIT_TRIGGER_REGION = 0x15,
    EVENT_PLAYER_FAIL_TRIGGER_REGION_RESTRICTION = 0x16,
    EVENT_PLAYER_ENTER_RESTRICTED_AREA = 0x17,
    EVENT_PLAYER_EXIT_RESTRICTED_AREA = 0x18,
    EVENT_MISSION_SUCCESS = 0x19,
    EVENT_MISSION_FAILURE = 0x1A,
    EVENT_TIMER_ELAPSED = 0x1B,
    EVENT_OBJECTIVE_COMPLETE = 0x1C,
    EVENT_MISSION_OBJECTIVE_COMPLETE = 0x1D,
    EVENT_MOVER_STREAM_IN = 0x1E,
    EVENT_RECRUITMENT = 0x1F,
    EVENT_ALERT_LEVEL_CHANGED = 0x20,
    EVENT_SQUAD_KILLED = 0x21,
    EVENT_SQUAD_MEMBER_KILLED = 0x22,
    EVENT_PLAYER_KILLS_VEHICLE = 0x23,
    EVENT_PLAYER_KILLS_HUMAN = 0x24,
    EVENT_ROAD_BECOMES_BLOCKED = 0x25,
    EVENT_BRIDGE_BECOMES_UNUSABLE = 0x26,
    EVENT_PLAYER_KILLS_VEHICLE_FROM_VEHICLE = 0x27,
    EVENT_VEHICLE_DAMAGE = 0x28,
    EVENT_PLAYER_ENTERS_VEHICLE = 0x29,
    EVENT_PLAYER_EXITS_VEHICLE = 0x2A,
    EVENT_NPC_ENTERS_VEHICLE = 0x2B,
    EVENT_MISSION_VRAIL_COMPLETE = 0x2C,
    EVENT_PLAYER_UNDER_ATTACK = 0x2D,
    EVENT_VEHICLE_UNDER_ATTACK = 0x2E,
    EVENT_PLAYER_DAMAGED_BY_EXPLOSION = 0x2F,
    EVENT_CONT_ATTACK_SQUAD_REACHED_END = 0x30,
    EVENT_PATROL_SQUAD_REACHED_NODE = 0x31,
    EVENT_WALKER_MOUNT_VEHICLE = 0x32,
    EVENT_HUMAN_USING_ACTION_NODE = 0x33,
    EVENT_SQUAD_MEMBERS_SPAWNED = 0x34,
    EVENT_PLAYER_GETS_SALVAGE = 0x35,
    EVENT_SATELLITE_REACHES_TARGET = 0x36,
    EVENT_MOVER_HUMAN_SPECIAL_COLLISION = 0x37,
    EVENT_PLAYER_ENTERS_CRITICAL_AREA = 0x38,
    EVENT_SQUAD_MEMBERS_DESPANED = 0x39,
    EVENT_NPC_DESPANED = 0x3A,
    EVENT_PLAYER_FIRES_WEAPON = 0x3B,
    EVENT_HUMAN_STOPPED_BEING_RENDERED = 0x3C,
    EVENT_USER_DEFINED = 0x3D,
    NUM_EVENT_TYPES = 0x3E,
};

enum event_result
{
    EVENT_IGNORED = 0x0,
    EVENT_HANDLED = 0x1,
    EVENT_OK = 0x2,
}; //Note: Apparently also is typedef for several types

struct event_data
{
    event_type type;
};

struct notify_info
{
    event_type type;
    event_result(__cdecl* callback)(event_data*, notify_info*);
    void* data;
};