return {
    ["Current"] = 4294967295,
    ["Standard"] = 0,
    ["Jump"] = 1,
    ["Fall"] = 2,
    ["Turret"] = 3,
    ["Dead"] = 4,
    ["Ladder"] = 5,
    ["PlayerPathing"] = 6,
    ["VehicleEntering"] = 7,
    ["VehicleSitting"] = 8,
    ["VehicleDriving"] = 9,
    ["VehicleExiting"] = 10,
    ["Spectator"] = 11,
    ["Cover"] = 12,
    ["AmmoBox"] = 13,
    ["MpDefuse"] = 14,
    ["ActionNode"] = 15,
    ["Satellite"] = 16,
    ["NumHumanStates"] = 17,
}