return {
    ["None"] = 4294967295,
    ["Bullet"] = 0,
    ["Launcher"] = 1,
    ["Thrown"] = 2,
    ["ThrownCharge"] = 3,
    ["ThrownMine"] = 4,
    ["ThrownGrenade"] = 5,
    ["Melee"] = 6,
    ["Sledgehammer"] = 7,
    ["Gutter"] = 8,
    ["Grinder"] = 9,
    ["ArcWelder"] = 10,
    ["NanoRifle"] = 11,
    ["MassDriver"] = 12,
    ["Harpoon"] = 13,
    ["SingularityBomb"] = 14,
    ["Repair"] = 15,
    ["Flame"] = 16,
}