#include "Functions.h"


F_Camera_Start_Slew_Mode Camera_Start_Slew_Mode;
F_Camera_Stop_Slew_Mode Camera_Stop_Slew_Mode;
F_Interface_Debug_Mode_Activate Interface_Debug_Mode_Activate;
F_Keen_Debug_WriteToLogFile Keen_Debug_WriteToLogFile;
F_Hud_Display_Distance Hud_Display_Distance;
F_Console_Init Console_Init;
F_Console_Activate Console_Activate;
F_Console_Deactivate Console_Deactivate;
F_Console_Printf Console_Printf;
F_Console_Display_Help Console_Display_Help;
F_Console_Command_Enable Console_Command_Enable;
F_Console_Do_Command Console_Do_Command;
F_Camera_First_Person_Pre_Process Camera_First_Person_Pre_Process;
F_Camera_Start_Third_Person Camera_Start_Third_Person;
F_Game_Print_Screen Game_Print_Screen;
F_camera_free_system_init camera_free_system_init;
F_camera_free_mode_init camera_free_mode_init;
F_console_chat_printf console_chat_printf;
F_unused_dcf_r_show_mem_usage unused_dcf_r_show_mem_usage;
F_rfg_dyn_get_active_destruction_frame rfg_dyn_get_active_destruction_frame;
F_rfg_dyn_reset_destruction_frame rfg_dyn_reset_destruction_frame;
F_rfg_dyn_system_shutdown rfg_dyn_system_shutdown;
F_get_screen_width get_screen_width;
F_console_is_active console_is_active;
F_debug_spew_projectile debug_spew_projectile;
F_debug_spew_game_io debug_spew_game_io;
F_rl_render_lib_get_metrics rl_render_lib_get_metrics;
F_profile_dump_info profile_dump_info;
F_vint_render_text vint_render_text;
F_xray_effect_start xray_effect_start;
F_xray_effect_stop xray_effect_stop;
F_camera_start_first_person camera_start_first_person;
F_camera_stop_first_person camera_stop_first_person;
F_key_down key_down;
F_game_render_set_bloom_exposure_factor game_render_set_bloom_exposure_factor;
F_game_render_set_hdr_state game_render_set_hdr_state;
F_game_render_2d_text game_render_2d_text;
F_ui_add_debug_text ui_add_debug_text;
F_get_depth_of_field_enabled get_depth_of_field_enabled;
F_set_depth_of_field_enabled set_depth_of_field_enabled;
F_character_controller_set_pos character_controller_set_pos; //IDA shows this as using __thiscall, but using that causes the game to immediately crash
F_fog_of_war_clear fog_of_war_clear;

F_Hud_Hide Hud_Hide;
F_game_render_set_fog_enabled game_render_set_fog_enabled;

F_explosion_create ExplosionCreate;
F_keen_graphics_beginframe GraphicsBeginFrame;
F_MouseGenericAutoCentering MouseGenericAutoCentering;
F_CameraViewDataSetView CameraViewDataSetView;
F_PlayerDoFrame PlayerDoFrame;
F_PlayerConstructor PlayerConstructor;
F_CharacterControllerSetPos CharacterControllerSetPos;

F_ObjectUpdatePosAndOrient ObjectUpdatePosAndOrient;

F_HavokBodySetPosition HavokBodySetPosition;
F_HavokBodyGetPositionAndOrient HavokBodyGetPositionAndOrient;

F_HavokBodySetPositionAndOrient HavokBodySetPositionAndOrient;

F_HumanUpdatePosAndOrient HumanUpdatePosAndOrient;
F_HumanTeleportUnsafe HumanTeleportUnsafe;
//F_HumanTeleport HumanTeleport;

/*Start of MP Detection Hooks*/
F_IsValidGameLinkLobbyKaiko IsValidGameLinkLobbyKaiko;
F_GameMusicMultiplayerStart GameMusicMultiplayerStart;
F_InitMultiplayerDataItemRespawn InitMultiplayerDataItemRespawn;
F_HudUiMultiplayerProcess HudUiMultiplayerProcess;
F_HudUiMultiplayerEnter HudUiMultiplayerEnter;
/*End of MP Detection Hooks*/

F_KeenGraphicsResizeRenderSwapchain KeenGraphicsResizeRenderSwapchain;
F_GameseqGetState GameseqGetState;

F_ObjectEnableOutline ObjectEnableOutline;
F_ObjectDisableOutline ObjectDisableOutline;
F_HumanEnableOutline HumanEnableOutline;
F_HumanDisableOutline HumanDisableOutline;
F_TargetOutlineAddObject TargetOutlineAddObject;