return {
    ["Invalid"] = 4294967295, --0xFFFFFFFF
    ["MpUseDisarm"] = 0,
    ["MpSwapBackpack"] = 1,
    ["MpModeSpecific"] = 2,
    ["Dialogue"] = 3,
    ["UseTurret"] = 4,
    ["UseEquippedItem"] = 5,
    ["UseNearestItem"] = 6,
    ["UseVehicle"] = 7,
    ["UseLadder"] = 8,
    ["UseAmmoBox"] = 9,
    ["ReleaseHostage"] = 10,
    ["UseBase"] = 11,
    ["StartMission"] = 12,
    ["StartDemolitionsMaster"] = 13,
    ["StartRidingShotgun"] = 14,
    ["StartHouseArrest"] = 15,
    ["StartOffensiveRaid"] = 16,
    ["Upgrade"] = 17,
    ["StartAreaDefense"] = 18,
    ["NumGeneralActionTypes"] = 19,
}